version: "3"
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
  app1:
    image: app1
    ports:
      - "8080:8080"
    container_name: application1
  app2:
    image: app2
    ports:
      - "8081:8080"
    container_name: application2
